version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    links:
      - consul
    ports:
      - "8080:8080"
  consul:
    image: progrium/consul
    container_name: consul
    command: -server -bootstrap -advertise 192.168.99.100
    logging:
        driver: json-file
    ports:
      - "8500:8500"
  servicio-producto:
    image: servicio-producto:latest
    container_name: servicioProducto
    logging:
       driver: json-file
    volumes:
      - ./:/app
    depends_on:
      - mysql
    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_ventas
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: db_ventas
  servicio-cliente:
    image: servicio-cliente:latest
    container_name: servicioCliente
    logging:
       driver: json-file
    volumes:
      - ./:/app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: db_ventas
  servicio-factura:
    image: servicio-factura:latest
    container_name: servicioFactura
    logging:
       driver: json-file
    volumes:
      - ./:/app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: db_ventas
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ventas-db:/var/liv/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_ventas
volumes:
  ventas-db:
